# Use an official Node.js runtime as the base image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Install dependencies
COPY package.json package-lock.json /app/

# Install the dependencies inside the container
RUN npm install

# Copy the rest of the project files into the container
COPY . /app/

# Expose the port that Next.js will run on
EXPOSE 3000

CMD ["npm", "run", "dev"]
