# Dev Stage: Use SDK image with tooling
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS dev

# Install required tools (e.g., for hot reload)
RUN dotnet tool install --global dotnet-watch \
    && apk add --no-cache bash curl

ENV PATH="$PATH:/root/.dotnet/tools"

# Copy everything into container (ensure to copy all the necessary files)
COPY . /app 

RUN dotnet restore /app/QuizAppApi.sln

# Set the working directory to the Api folder
WORKDIR /app/Api

# Start with hot reload enabled
CMD ["dotnet", "watch", "run"]